#!/bin/sh

# Avoid USB resets
echo "auto" > /sys/bus/usb/devices/3-1/power/control
echo "3000" > /sys/bus/usb/devices/3-1/power/autosuspend_delay_ms
echo "enabled" > /sys/bus/usb/devices/3-1/power/wakeup
echo "1" > /sys/bus/usb/devices/3-1/avoid_reset_quirk
echo "0" > /sys/bus/usb/devices/3-1/power/persist
